---
name: Monitor Checks

on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/DevSkim-Action@v1
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: devskim-results.sarif
  self:
    runs-on: ubuntu-latest
    steps:
      - name: Testing self
        uses: crainte/gha-status-check-result@main
        id: testing
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          apiKey: ${{ secrets.GIPHY_API_KEY }}
