---
name: Monitor Checks

on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master

  giphy:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting
        id: waiting
        uses: "WyriHaximus/github-action-wait-for-status@v1.3.1"
        with:
          ignoreActions: giphy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Status Giphy
        uses: jzweifel/pr-status-giphy-action@master
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
