---
name: Monitor Checks

on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  self:
    runs-on: ubuntu-latest
    steps:
      - name: Testing self
        uses: crainte/gha-status-check-result@0.0.5
        id: testing
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
