---
name: Monitor Checks

on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master

  self:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting
        id: waiting
        uses: "WyriHaximus/github-action-wait-for-status@v2"
        with:
          ignoreActions: self
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Testing self
        uses: crainte/gha-status-check-result@main
        id: testing
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          apiKey: ${{ secrets.GIPHY_API_KEY }}
